CREATE TABLE TB_STUDENT(
 	STD_NO NUMBER PRIMARY KEY,
 	STD_NAME VARCHAR2(30) NOT NULL,
 	STD_AGE NUMBER NOT NULL,
 	STD_GENDER CHAR(1) CHECK(STD_GENDER IN('M','F')) GENDER,
 	STD_SCORE CHAR(1) CHECK(STD_SCORE IN('A', 'B', 'C', 'D', 'E')) SCORE
);

SELECT * FROM TB_STUDENT
ORDER BY STD_NO ASC; 

DELETE FROM TB_STUDENT WHERE STD_NO = 3;

INSERT INTO TB_STUDENT
VALUES(1, '홍길동', 19, 'M', 'B');
SELECT * FROM TB_STUDENT;
COMMIT;











